name: 'Test and Publish'

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.302

      - name: Test
        run: dotnet test

  windows10:
    name: 'Publish for Windows'
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.302

      - name: Publish
        run: dotnet publish -c release -r win10-x64

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: DesktopApp/bin/Release/net5.0/win10-x64/publish

  linux:
    name: 'Publish for Linux'
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.302

      - name: Publish
        run: dotnet publish -c release -r linux-x64

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: DesktopApp/bin/Release/net5.0/linux-x64/publish

  macos:
    name: 'Publish for MacOS'
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.302

      - name: Publish
        run: dotnet publish -c release -r osx-x64

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: DesktopApp/bin/Release/net5.0/osx-x64/publish
